[ Onboarding - Nuova pagina profilo] Added new profile page, taking d…
RiccardoMolinari95/io-app pull request #1
Opened 2024-10-01 10:04 UTC by RiccardoMolinari95

Onboarding - Nuova pagina profilo

## Short description
Added new profile page, taking data from a separate stream. The new profile page displays:

- first and last name
- tax code
- email
- date of birth
The feature can be activated via the switch in Settings -> Preferences -> Enable new profile page
Enabling the feature will display a button with the profile icon in the navigator tab

## How to test
Enable "New Profile page"

2024-10-02 13:06 UTC, hevelius reviewed
What do you think to see the "new profile" a new feature in io-app? As you cans ee the codebase is organized by features. In the ts/features folder there are the mainly features of IO. For ex. the new profile, code, logic etc... could be in the ts/features/newProfile/ and protected behind a local feature flag

2024-10-03 08:12 UTC, hevelius requested changes

2024-10-03 08:12 UTC, hevelius commented on ts/features/newProfile/store/reducers/newProfile.ts
What do you think to add a unit test for this reducer?

2024-10-03 08:18 UTC, RiccardoMolinari95 commented on ts/features/newProfile/store/reducers/newProfile.ts
Yes, sounds good

2024-10-03 13:59 UTC, hevelius approved these changes

2024-10-03 14:04 UTC, RiccardoMolinari95 commented
[ Onboarding - Nuova pagina profilo]

2024-10-04 10:50 UTC, merged