Feature flusso cancellazione profilo
RiccardoMolinari95/io-app pull request #3
Opened 2024-10-01 14:04 UTC by RiccardoMolinari95

Onboarding - Flusso Cancellazione Profilo

## Short description
Added flow to delete profile, via two possibilities:
- added a button "Elimina il tuo profilo" in “Portafoglio”
- by moving the switch from “off” to “on” on the new profile page.

## How to test
Delete the profile via the newly added button and continue with the deletion via the various confirmation screens. Once deleted , go to the new profile page and see if the loader is loading and the switch is "on".
Return to the “Portfolio” section and click the “Retrieve Profile” button to cancel the deletion request by accepting the alert

2024-10-08 11:05 UTC, hevelius requested changes

2024-10-08 11:05 UTC, hevelius commented on ts/navigation/ProfileNavigator.tsx
What do you think to use a dedicated navigator instead to use the main navigator for profile?

2024-10-08 12:37 UTC, RiccardoMolinari95 commented on ts/navigation/ProfileNavigator.tsx
Yes, right

2024-10-11 06:34 UTC, hevelius approved these changes

2024-10-11 06:40 UTC, merged